import "~/styles/globals.css";

import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable} flex flex-col gap-4`}>
        <nav className="flex w-full items-center justify-between border-b border-white p-4">
          <p className="text-2xl font-semibold">Gallery App</p>
          <p>Disconnect</p>
        </nav>
        {children}
      </body>
    </html>
  );
}
